export const verses = [
  { text: 'The Lord is my shepherd; I shall not want.', reference: 'Psalm 23:1' },
  { text: 'Be still, and know that I am God.', reference: 'Psalm 46:10' },
  { text: 'This is the day which the Lord hath made; we will rejoice and be glad in it.', reference: 'Psalm 118:24' },
  { text: 'Trust in the Lord with all thine heart; and lean not unto thine own understanding.', reference: 'Proverbs 3:5' },
  { text: 'In all thy ways acknowledge him, and he shall direct thy paths.', reference: 'Proverbs 3:6' },
  { text: 'The name of the Lord is a strong tower: the righteous runneth into it, and is safe.', reference: 'Proverbs 18:10' },
  { text: 'For I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil.', reference: 'Jeremiah 29:11' },
  { text: 'The Lord is good unto them that wait for him, to the soul that seeketh him.', reference: 'Lamentations 3:25' },
  { text: 'Blessed are the pure in heart: for they shall see God.', reference: 'Matthew 5:8' },
  { text: 'Ask, and it shall be given you; seek, and ye shall find.', reference: 'Matthew 7:7' },
  { text: 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.', reference: 'Matthew 11:28' },
  { text: 'With God all things are possible.', reference: 'Matthew 19:26' },
  { text: 'Thou shalt love thy neighbour as thyself.', reference: 'Matthew 22:39' },
  { text: 'What things soever ye desire, when ye pray, believe that ye receive them.', reference: 'Mark 11:24' },
  { text: 'For with God nothing shall be impossible.', reference: 'Luke 1:37' },
  { text: 'Glory to God in the highest, and on earth peace, good will toward men.', reference: 'Luke 2:14' },
  { text: 'For where your treasure is, there will your heart be also.', reference: 'Luke 12:34' },
  { text: 'For God so loved the world, that he gave his only begotten Son.', reference: 'John 3:16' },
  { text: 'He must increase, but I must decrease.', reference: 'John 3:30' },
  { text: 'I am the light of the world: he that followeth me shall not walk in darkness.', reference: 'John 8:12' },
  { text: 'Ye shall know the truth, and the truth shall make you free.', reference: 'John 8:32' },
  { text: 'Let not your heart be troubled: ye believe in God, believe also in me.', reference: 'John 14:1' },
  { text: 'Peace I leave with you, my peace I give unto you.', reference: 'John 14:27' },
  { text: 'I am the vine, ye are the branches.', reference: 'John 15:5' },
  { text: 'Greater love hath no man than this, that a man lay down his life for his friends.', reference: 'John 15:13' },
  { text: 'These things I have spoken unto you, that in me ye might have peace.', reference: 'John 16:33' },
  { text: 'We know that all things work together for good to them that love God.', reference: 'Romans 8:28' },
  { text: 'If God be for us, who can be against us?', reference: 'Romans 8:31' },
  { text: 'Be not overcome of evil, but overcome evil with good.', reference: 'Romans 12:21' },
  { text: 'Let all your things be done with charity.', reference: '1 Corinthians 16:14' },
  { text: 'My grace is sufficient for thee: for my strength is made perfect in weakness.', reference: '2 Corinthians 12:9' },
  { text: 'Stand fast therefore in the liberty wherewith Christ hath made us free.', reference: 'Galatians 5:1' },
  { text: 'Bear ye one another\'s burdens, and so fulfil the law of Christ.', reference: 'Galatians 6:2' },
  { text: 'Be ye kind one to another, tenderhearted, forgiving one another.', reference: 'Ephesians 4:32' },
  { text: 'Walk in love, as Christ also hath loved us.', reference: 'Ephesians 5:2' },
  { text: 'I can do all things through Christ which strengtheneth me.', reference: 'Philippians 4:13' },
  { text: 'And the peace of God, which passeth all understanding, shall keep your hearts and minds.', reference: 'Philippians 4:7' },
  { text: 'Set your affection on things above, not on things on the earth.', reference: 'Colossians 3:2' },
  { text: 'And whatsoever ye do, do it heartily, as to the Lord.', reference: 'Colossians 3:23' },
  { text: 'Rejoice evermore. Pray without ceasing. In every thing give thanks.', reference: '1 Thessalonians 5:16–18' },
  { text: 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.', reference: '2 Timothy 1:7' },
  { text: 'Jesus Christ the same yesterday, and to day, and for ever.', reference: 'Hebrews 13:8' },
  { text: 'Every good gift and every perfect gift is from above.', reference: 'James 1:17' },
  { text: 'Draw nigh to God, and he will draw nigh to you.', reference: 'James 4:8' },
  { text: 'Casting all your care upon him; for he careth for you.', reference: '1 Peter 5:7' },
  { text: 'We love him, because he first loved us.', reference: '1 John 4:19' },
  { text: 'God is love; and he that dwelleth in love dwelleth in God.', reference: '1 John 4:16' },
  { text: 'Behold, I make all things new.', reference: 'Revelation 21:5' }
];
